name: "Konst och Ansvar"
tagline: "Konstnärliga lösningar med ansvar"
author: "Konst och Ansvar"
email: "info@konstochansvar.se"
phone: ""
address: ""
social:
  facebook: ""
  instagram: ""
  linkedin: ""

